name: GitOps bump Helm tags
description: "Update values/*/<env>/version.yaml image tags and commit"

inputs:
  env_name:
    description: "Environment name (sandbox|development|uat|production)"
    required: true
  apps_json:
    description: "JSON array of apps to bump (e.g. [\"web-ui\",\"api\"])"
    required: true
  image_tag:
    description: "Image tag to set (usually short SHA)"
    required: true
  commit_message:
    description: "Commit message for the bump"
    required: true
  rebase_main:
    description: "If true, rebase local checkout onto origin/main before changes"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Rebase onto latest main
      if: ${{ inputs.rebase_main == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        git fetch origin main
        git pull --rebase origin main

    - name: Install yq
      uses: mikefarah/yq@v4

    - name: Update all values/*/${{ inputs.env_name }}/version.yaml
      shell: bash
      env:
        ENV_NAME: ${{ inputs.env_name }}
        APPS_JSON: ${{ inputs.apps_json }}
        IMAGE_TAG: ${{ inputs.image_tag }}
      run: |
        set -euo pipefail

        if [[ -z "${APPS_JSON:-}" ]]; then
          echo "apps_json input is required" >&2
          exit 1
        fi

        mapfile -t APPS < <(jq -r '.[]' <<<"$APPS_JSON")
        if [[ ${#APPS[@]} -eq 0 ]]; then
          echo "No apps provided in apps_json; skipping."
          exit 0
        fi

        updated=0
        for app in "${APPS[@]}"; do
          version_file="values/${app}/${ENV_NAME}/version.yaml"
          [[ -f "$version_file" ]] || { echo "Missing version file for app '$app': $version_file" >&2; exit 1; }

          changed=0
          
          # Version files are not uniform:
          # - some use: image.tag
          # - others use: service.image.tag
          if [[ "$(yq e '.service.image.tag' "$version_file")" != "null" ]]; then
            current_image_tag="$(yq e '.service.image.tag' "$version_file")"
            if [[ "$current_image_tag" != "$IMAGE_TAG" ]]; then
              yq -i '.service.image.tag = strenv(IMAGE_TAG)' "$version_file"
              changed=1
            fi
          elif [[ "$(yq e '.image.tag' "$version_file")" != "null" ]]; then
            current_image_tag="$(yq e '.image.tag' "$version_file")"
            if [[ "$current_image_tag" != "$IMAGE_TAG" ]]; then
              yq -i '.image.tag = strenv(IMAGE_TAG)' "$version_file"
              changed=1
            fi
          else
            echo "No supported image tag key found in $version_file (expected image.tag or service.image.tag)" >&2
            exit 1
          fi

          # Update migrations image tag
          export MIGRATION_TAG="${app}-${IMAGE_TAG}"
          if [[ "$(yq e '.service.migrations.image.tag' "$version_file")" != "null" ]]; then
            current_migration_tag="$(yq e '.service.migrations.image.tag' "$version_file")"
            if [[ "$current_migration_tag" != "$MIGRATION_TAG" ]]; then
              yq -i '.service.migrations.image.tag = strenv(MIGRATION_TAG)' "$version_file"
              changed=1
            fi
          elif [[ "$(yq e '.migrations.image.tag' "$version_file")" != "null" ]]; then
            current_migration_tag="$(yq e '.migrations.image.tag' "$version_file")"
            if [[ "$current_migration_tag" != "$MIGRATION_TAG" ]]; then
              yq -i '.migrations.image.tag = strenv(MIGRATION_TAG)' "$version_file"
              changed=1
            fi
          fi

          if [[ $changed -eq 1 ]]; then
            updated=$((updated + 1))
          fi
        done

        if [[ $updated -eq 0 ]]; then
          echo "No updates performed."
          exit 0
        fi

    - name: Commit bumps
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: ${{ inputs.commit_message }}

