apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    {{- include "web-ui.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ tpl ($val | toString) $ | quote }}
  {{- end }}
